### ISSUE TITLE
💡 RFC: Allow for custom routes rather than file-based.

### ISSUE THREAD

**Issue by vtinev** [snowpackjs/astro#1039]
### Background & Motivation

It would be nice if developers can choose a custom URL rather than relying on the file-based one. For example, currently the translations for the docs are directly in the pages folder so you can do `https://docs.astro.build/de/getting-started`. It would be cleaner if we could put all of the different translations in one folder and still get `https://docs.astro.build/de/getting-started` rather than `https://docs.astro.build/translations/de/getting-started`.

There are more than 6000 languages. A number of 100 translations is realistic for a heavily used project, that's a lot of folders to navigate through.

### Possible solutions
Maybe if a route variable is present in the `.MD` file, the URL won't be affected by the path.

![image](https://user-images.githubusercontent.com/54780475/128459704-622a7a21-995c-4a2b-a879-8a9c9718a7fc.png)

### Alternatives considered
A separate file to define all routes?

### Risks, downsides, and/or tradeoffs
Sorry if that's already possible and I couldn't find it.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
A little sneak peak of `v0.19` is an improvement to Astro routing! Now you can more-easily generate pages on-the-fly with a dynamic page: https://github.com/snowpackjs/astro/blob/main/docs/src/pages/core-concepts/routing.md

You can read a little more about the thinking in the previous RFC here: https://github.com/snowpackjs/astro/issues/1004

So that’s what we have for now. To your problem of “A number of 100 translations is realistic for a heavily used project, that's a lot of folders to navigate through,“ I believe the new routing structure will help, but perhaps you want more! Our long-term goal is to have a more server-like environment for Astro so that more can be generated on-the-fly and you never have to deal with this issue. This doesn’t have an RFC yet because we’re still thinking through it internally, but that’s been our plan from day 1 and we will absolutely share more about this as it gets closer.

If it’s all right with you, I’m going to close this RFC in favor of the upcoming dynamic routing, and hopefully the promise of “even more coming soon“ works! But please let me know if I’m missing something, or if you’d like to give feedback on the new routing paradigm linked.

**Comment by n7trd** [comment]
@drwpow 
Im already using dynamic routes, really like the feature. The issue with file-based routing as the only option remains.

If the contents are saved as a files (.md or .astro) in the pages directory, file-based routing is the best solution.   
All the examples and the astro site are build this way and this makes a lot of sense.

If however, you fetch all of your contents and different languages from an headless cms, things looks different.

I would need to copy and past a lot of the same pages to different folder to with (sometimes) different names to generate the needed routes.
Which is obviously really bad to maintain.

The other solution would be to put the pages in the components folder. And make something like this with the pages folder to generate the routes:

```
en/...
en/page3-othername.astro  page3 component  with "en" prop
en/page2-othername.astro  page2 component  with "en" prop
en/page1-othername.astro  page1 component  with "en" prop
en/index.astro -> home component with "en" prop
...
page3.astro -> page3 component with "de" prop
page2.astro -> page2 component with "de" prop
page1.astro -> page1 component  with "de" prop
index.astro -> home component with "de" prop
```

where each page **only** contains:

```
---
import SomePage from "../components/pages/some-page.astro";
---

<SomePage language="de"/>
````
Thats a lot better to maintain.

But i still would prefer to opt out of file-routing and create something like astro.routes.mjs where i can define all the routes in one file an map them to the related components.

**Comment by drwpow** [comment]
@n7trd in your scenario could you simply do:

```
src/pages/[en]/[...page].astro
```

And use the last part of the segment to load the appropriate page from your CMS? I still believe you could fetch content that way without having to manage all these files, right?

**Comment by n7trd** [comment]
Thanks! I tried your suggestion above with dynamic routing. Seem to work well so far. 

I tried `src/pages/[lang]/[...page].astro` to generate routes for this:

```
de/page1
de/...
page1
...
```
The `de `route works. But i can't catch the "default" routes. Cause [lang] needs an value. 

```
src/pages/[...routes]
```
don't work for the same reason. Things like `mysite.com/de` works but not `mysite.com`.

Hope i didn't overlooked something...

**Comment by drwpow** [comment]
> But i can't catch the "default" routes. Cause [lang] needs an value.

Ah sorry; I missed that you had a default `lang` in which case I’d do exactly what you said with `src/pages/[...routes]`. It’s just a little extra work figuring out if that first segment is a language, but hopefully not too bad! This is hopefully exactly the usecase we’re trying to address.

I know the routing paradigm is still new, but we’re hoping to document it better and we’d like to commit to this pattern long-term. Would love your help in adding to the docs (or maybe an `examples/i18n` project!) that encourages some good patterns that you’re figuring out now!
