### ISSUE TITLE
💡 RFC: Astro.resolve

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#1071]
### Background & Motivation

There are been many issues where people expected to be able to reference a file relative to the current .astro file like so:

```js
<img src="../images/penguin.png" />
```

However we do not modify URLs for a few reasons:

1. Relative links are valid and used in HTML. How do we know if the user wants it relative to the .astro file or relative to the page URL?
2. We would need to special-case certain elements like `img` and `link` to achieve this.
3. Unknown elements and Components would not get the same treatment, creating inconsistency.
4. If someone used a variable it would not work as intended.

### Possible solutions

I propose a `Astro.resolve(path: string): string` function which takes a path and resolves it relative to the current .astro file. You can use it like so:

```js
<img src={Astro.resolve('../images/penguin.png')} />
```

This can be used anywhere in the .astro file, no-special casing required.

### Alternatives considered

Considered a special Image component, but decided a lower-level API would be better to cover all possible usages. An `Image` component is likely still coming, and might do this by default (future RFC to discuss that).

### Risks, downsides, and/or tradeoffs

The only downside I can think of is that high-level components/apis might still be desirable to cover common cases like `Image` or `Script`.

### Open Questions

Currently there's not an obvious way to implement this and might need a snowpack change to expose the current .astro file's browser URL.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Some thoughts:
- Strong +1 to solving this problem, not being able to do relative imports inside of components has been a real pain for users.
- I like this solution, feels really straightforward and easy to document.
- As a part of this solution, can we talk about warning (or maybe even erroring) if you send a relative url to `img src`, `script src`, `link`, etc?
- how would this work with `buildOptions.site`? Assuming this would return absolute urls prefixed with the correct root during build? (`/docs/*` instead of `/*`).

Also:
- Re Risks: I see this as unlocking a high-level component down the road, instead of blocking it in any way. I assume some `<Image src="./..." />` component it would use a similar feature internally.
- Re Alternatives: Its worth mentioning the `import someImageUrl from './foo.png'` alternative since we did talk that through and Next.js does support that. I think we landed on that being a future option that we could also support, but wanted import type assertions to land in the spec first.

**Comment by jasikpark** [comment]
How is this different from the current ESM syntax? https://docs.astro.build/guides/imports#other-assets

**Comment by FredKSchott** [comment]
hmm, not sure if that section is correct? If it does work, then the URL should be `/_astro/src` instead of `/src`. Either way, we should test to confirm.

**Comment by jasikpark** [comment]
I definitely think I like the api of that.. "if we don't directly support an import like css and js, make the import a link to the built asset" makes sense to me. 

Isn't that yoinked from Vite? Maybe it'd be useful to see how well that's worked for them?

**Comment by jonathantneal** [comment]
Thank you for proposing this, @matthewp. I have wanted this for an `Image` component.

For the record, there are 3 kinds of paths I have found myself accessing.

1. The file path to the current file. This is available to me using `import.meta.url`.
2. The http path to the current page. This is available to me in components using `props[Symbol.for('astro.context')]`.
3. The virtual path to the current page. This is not available to me, and this is what I would expect `Astro.resolve()` to provide. These paths currently start with `/_astro/`.

---

### Alternative: `import.meta.astro`

An alternative would be to hydrate `import.meta` with something like `import.meta.astro`.

```tsx
const { page, http, file } = import.meta.astro

console.log(page) // URL of the current page
console.log(http) // URL of the current URL, otherwise accessible with props[Symbol.for('astro.context')]
console.log(file) // URL of the current file, otherwise accessible with import.meta.url


```

---

### Additional suggestion: namespaced target attributes

An additional suggestion, pointed at your original motivation, is to provide a namespace hook for built-in elements. For instance, what if `src:from` or `href:from` resolved from the currently resolved page?

```html
<img src:from="/path/relative/to/page" />
<link href:from="/path/relative/to/page" />

<!-- normal usage remains unchanged -->
<img src="/path/relative/to/public" />
<link href="/path/relative/to/public" />
```

**Comment by matthewp** [comment]
Note that this needs warning for common attributes like `<img src="../rel" />`

**Comment by coelmay** [comment]
Not sure if this is relevant to this issue or if I should create a new one.

I am wanting to have `<img src="/img/path/to/image.jpg">` where `/img/` is proxied via Netlify Rewrite/Proxy e.g.

```toml
[[redirects]]
  from = "/img/*"
  to = "https://my-image-provider.com/<username>/:splat"
  status = 200
```
However, when I attempt to build with Astro I get `could not find <image.jpg>` as it doesn't exist locally. I can (obviously) get around this by using the full URL instead of proxying.

These images are in a product template, so only need to disable resolution on them (other images will come from `/public`. Something like `<img no-resolve src="/img/path/to/image.jpg"/>` would work for me, allow resolution of other images in the template/component etc.

**Comment by jasikpark** [comment]
> Not sure if this is relevant to this issue or if I should create a new one.
> 
> 
> 
> I am wanting to have `<img src="/img/path/to/image.jpg">` where `/img/` is proxied via Netlify Rewrite/Proxy e.g.
> 
> 
> 
> ```toml
> 
> [[redirects]]
> 
>   from = "/img/*"
> 
>   to = "https://my-image-provider.com/<username>/:splat"
> 
>   status = 200
> 
> ```
> 
> However, when I attempt to build with Astro I get `could not find <image.jpg>` as it doesn't exist locally. I can (obviously) get around this by using the full URL instead of proxying.
> 
> 
> 
> These images are in a product template, so only need to disable resolution on them (other images will come from `/public`. Something like `<img no-resolve src="/img/path/to/image.jpg"/>` would work for me, allow resolution of other images in the template/component etc.

It'd be interesting if you could augment Astro.resolve for that usecase 😅
