### ISSUE TITLE
💡 RFC: Server-Side Rendering On Demand

### ISSUE THREAD

**Issue by OfekA** [snowpackjs/astro#1119]
### Background & Motivation

I think astro is an amazing project that will push web performance forward. What I'm mostly lacking at the moment is the ability to run astro in SSR mode and not pre-generate all the pages in advance. This current limitation is preventing me to use it in many use cases.

### Possible solutions

A render API, similar to what Nuxt provides: https://nuxtjs.org/docs/2.x/internals-glossary/nuxt-render

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
RFC Call decision: we really love this idea, and think it could be useful to the Astro project as a whole. But there are a few considerations. First, we have an Astro server runtime on our list as a long-term project goal. Likely won’t happen as part of 1.0, but we’ve been designing it from day 1 to eventually support this usecase.

Short-term, I think we could probably see something implemented if it’s well-defined in scope. And to that end, I’d like to start a thread in #ideas-and-suggestions in Discord to flesh this out a bit more. Will post a link to that shortly.

**Comment by drwpow** [comment]
Ah forgot to check back in! We have an `#ssr` channel in our Discord meant for discussing this. We are open to an RFC for this! But let’s revisit this a) when the new Vite + compiler is merged into main, and b) driven from conversations in #ssr, along with a clearer implementation of how this could be accomplished.

**Comment by ThatGuySam** [comment]
This may not be the correct location but this also is huge for generating endpoints after the initial build, on the first page load, which is a must when static sites start approaching 5k+ pages, otherwise, you have to figure out a way to facilitate 60min+ build times, even on faster generators like Astro or Eleventy. 

Netlify's max build limit is 30mins and I believe Vercel's is 60mins. 

Here are some of the different approaches and respective documentation: 

[Netlify On-Demand Build / Distributed Persistent Rendering](https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds/)

[Next.js Incremental Static Regeneration](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration)

[Gatsby Deferred Static Generation](https://www.gatsbyjs.com/blog/deferred-static-generation-guide/)

**Comment by alex-grover** [comment]
@drwpow sorry for reviving this old issue, but I'm not on Discord. Now that Astro has SSR, is this something that's in discussion? This feature is extremely useful in other frameworks.

**Comment by davidmyersdev** [comment]
For others that are looking for info about ISR in Astro: https://github.com/withastro/roadmap/issues/698
