### ISSUE TITLE
💡 RFC: Minifying Classnames

### ISSUE THREAD

**Issue by RafidMuhymin** [snowpackjs/astro#1138]
### Background & Motivation

The class names generated by Astro and written by the developer usually contain tens of characters. But the browser doesn't need them to render correctly. So, they should be minified/mangled to reduce the size of the stylesheet and the markup file.

Input:
```astro
<html>
      <head>
        <link rel="stylesheet" href="style.css"></link>
        <style>
          .text-red {
            color: red;
          }
        </style>
      </head>
      <body>
        <h1 class="text-red">Red Heading</h1>
        <p class="text-blue">Blue Paragraph</p>
      </body>
    </html>
```

Output:
```astro
<html>
      <head>
        <link rel="stylesheet" href="style.css"></link>
        <style>
          .b {
            color: red;
          }
        </style>
      </head>
      <body>
        <h1 class="b">Red Heading</h1>
        <p class="a">Blue Paragraph</p>
      </body>
    </html>
```

### Possible solutions
After generating static HTML, the compiler will analyze the markup and the internal and external styles and then minify the class names that it found.

### Alternatives considered
One alternative is that when the compiler will generate the scoped class names, it'll minify them. I think it's the one easier to implement.

### Risks, downsides, and/or tradeoffs
The compiler won't find the class names used in the dynamic portions of the website. So, they can't be used there. And as the scoped styles don't work outside the current component the developer already knows that they don't work.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
I love considerations like these! This is a very ”nerdy” detail that is 100% what we want to think about with Astro. With this point, I want to share 2 points that were part of the current classname hashing, that also factor in here: efficiency and reliability.

Efficiency-wise, meaning, _what’s the payoff_, it’s worth noting that any repeated character string is very “gzippable.“ So even if a class name is 10 characters long, as long as it repeats (which it will), that’ll compress very, very well. And [gzipping pays dividends over minification](https://css-tricks.com/the-difference-between-minification-and-gzipping/). AFAIK classname length isn’t a performance issue with browsers, so I think this is purely only a network optimization. FWIW Astro already does minify CSS, so this would be only an incremental minification improvement. And I think we’d need to see how this impacts the **gzipped** size since that’s what gets sent over the network.

Reliability-wise, meaning _is this error-prone_, the CSS hash we generate currently is collisionproof—there is a 0% chance another component will have the same hash. The shorter you make that hash, the higher the chance of collision. It’s hard to do in the compiler since it can’t know about all other components at any given time, but even if we were to minify this hash only for production builds, we’d still have to guarantee that the new classes don’t conflict with any _other_ class names you wrote manually (something we don’t check now), and we’d have to guarantee that all the new “hashes” don’t conflict with each other, too. So some minimum length would probably still be required.

So all that to say, “could our unique hashes be shorter?” I think so! I think we could probably trim the length. But I’d also like to see what the payoff would be first.

**Comment by FredKSchott** [comment]
I've tried to be pretty strict about kicking all "nice-to-have" optimizations that also increase complexity off until post v1.0.  Like @drwpow says, gzip makes the performance impact here almost zero, and as an appeal to authority: svelte has had hard-coded "svelte-*" classes since forever. 

Not opposed to revisiting this eventually, but I feel strongly enough about not discuss this until v1.0 has landed (or at least a release candidate)
