### ISSUE TITLE
RFC Call: Aug 24, 2021

### ISSUE THREAD

**Issue by drwpow** [snowpackjs/astro#1144]
## When / Where
- 2p EDT, 11a PDT
- On Discord, #events channel

## Agenda
https://github.com/snowpackjs/astro/issues?q=is%3Aopen+is%3Aissue+label%3Arfc-discuss
Want to see something discussed? Comment below and we can add a tag
- #708
- #965
- #883
- #706
- #963
- #495
- #1160

**Comment by FredKSchott** [comment]
@matthewp I'd like to briefly attempt to get consensus on https://github.com/snowpackjs/astro/issues/1212, given that there's already a PR out. 

I know it was just opened now so if consensus isn't possible I'm fine to wait a week or potentially resolve via PR thread instead. But i would at least like to bring it up so that people see it!
