### ISSUE TITLE
🐛 BUG: Theme picker in docs is broken

### ISSUE THREAD

**Issue by MarcusOtter** [snowpackjs/astro#1146]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

The theme picker broke in docs with this change: https://github.com/snowpackjs/astro/pull/1015/files#diff-c6a91ae0790426049fc887f4548a7db7d5ba07139a97b93c9f46c115f19b09faL67

It works again when that change is reverted.

### Steps to Reproduce

1. Build the docs project from `main`
2. Go to any page
3. Click the theme buttons
4. Nothing happens

**Comment by FredKSchott** [comment]
Sorry, I can't reproduce locally or on the hosted `main` branch: https://next.docs.astro.build/getting-started

Can you try re-running `yarn && yarn build` in the project to confirm that you're on the latest build locally? Otherwise, you may have uncovered a Windows-only error. Would love your help debugging to find out what's going on if that's the case. In the past, that was due to an error in IntersectionObservers. (maybe you're in an outdated browser? https://caniuse.com/intersectionobserver

**Comment by MarcusOtter** [comment]
I should be the one to apologize! I tried now with a fresh `git clone`, both at the current `main` and also at the commit where `main` was when I created this issue, but wasn't able to reproduce. I was on the latest commit locally when I filed this issue, but I *think* the problem was that I had to run `yarn build` in the **_root folder_** (not `docs/`) again since I hadn't done that for a while. False alarm 😄
