### ISSUE TITLE
💡 RFC: Support fallback for getStaticPaths like Next.js

### ISSUE THREAD

**Issue by thanhtoan1196** [snowpackjs/astro#1153]
### Background & Motivation

Support fallback for getStaticPaths like Next.js: https://nextjs.org/docs/basic-features/data-fetching#the-fallback-key-required
Example: { fallback: blocking } will server-render pages on-demand if the path doesn't exist.

### Possible solutions

See how Next.js works

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by tony-sull** [comment]
Nice, I hadn't actually seen that option in Next before!  Right now Astro is focused on static generation so a fallback wouldn't really fit, but this is would be a great feature to consider as SSR comes up on the feature list :+1: 

RFC #1119 is related and actually just talked about on yesterday's RFC call.  If you're in the Discord there's actually a new thread started to discuss an Astro SSR API as well, this would be great feedback to add to the conversation!

**Comment by FredKSchott** [comment]
+1! This is out of scope for the moment since the SSR feature that this would require is considered post-v1.0 (see Tony's post above). But, we have an #ideas-and-suggestions channel in Discord + a dedicated #dynamic-routing channel where this is being discussed. Would love your thoughts there if you'd like to join!
