### ISSUE TITLE
💡 RFC: router required

### ISSUE THREAD

**Issue by amancoder28** [snowpackjs/astro#1353]
### Background & Motivation

I'm recently working with solid.js and it's router (solid app router) is really awesome for me. But When i come to astro, i have loosed the routing functionality (single page app like routing, without page reload). I know solid.js do routing because js is the main the driver of the web app. In astro, this is inversed, html is the main thing. But i really like a single page application type routing! its awesome and its a core thing!

### Proposed Solution

> creating a router for astro js which wraps pages and do the routing!

### Help make it happen!

- [X] I am not willing to submit a PR to implement this change.

**Comment by RafidMuhymin** [comment]
Have you tried using the `astro-spa` package?

**Comment by coelmay** [comment]
> In astro, this is inversed, html is the main thing

It does say on the Astro homepage **Build faster websites with less client-side Javascript**.

I don't see Astro as another framework for generating SPAs. *Routing* is done by inserting an `<a>` and linking to (and navigating to) another page without JS doing any routing.

> its awesome and its a core thing!

This is not something I can agree with. JS has its place alongside HTML and CSS, but I don't believe it is core, especially when it comes to rendering HTML, and navigating.

**Comment by mzaini30** [comment]
Maybe, you can use Turbolinks.

**Comment by eyelidlessness** [comment]
Looking at it the other way around, if what you want is a SPA, Astro’s core selling point of partial hydration doesn’t benefit you much. First page load may be more efficient, but you’re likely looking at full page hydration or something like React Server Components for any subsequent navigation.

Turbolinks likely are a better fit.

**Comment by matthewp** [comment]
Thanks for filing the issue! We do need a concrete proposal to move forward with an RFC however. Since you checked the box of not being able to implement I assume you are looking for others to move on an idea. There is one similar RFC with a proposal: #1216, you might participate in that.

Otherwise Discord is a good place to bring up ideas that maybe haven't been flushed out, there is an [ideas-and-suggestions](https://discord.com/channels/830184174198718474/872579324446928896) channel just for that.
