### ISSUE TITLE
🐛 BUG: html styles added in layouts apply to all pages

### ISSUE THREAD

**Issue by TheoBr** [snowpackjs/astro#1354]
### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Expected behavior: Applying styles to `html` and `body` tags in Layout will only affect `html` and `body` when that layout is imported

Observed behavior: Making any change to `html` or `body` in a layout astro file will affect all pages, regardless of if it is imported

### Steps to Reproduce

See commit on this branch:
https://github.com/TheoBr/t3-astro/pull/2

### Link to Minimal Reproducible Example (Optional)

https://github.com/TheoBr/t3-astro/pull/2

**Comment by drwpow** [comment]
I am able to reproduce in the production build. When styles are bundled together, global styles may apply to pages that they weren’t originally written to.

Off the top of my head there may be a few solutions:

1. Implement #2 here: https://github.com/snowpackjs/astro/issues/918#issuecomment-917115413. While this may make the caching story _technically_ worse, it does overall seem to drastically improve cold-hit load times for sites and seems like a net win. But this comes with a caveat: as this solution is not fully fleshed out, one possible implementation of this may not address the underlying issue here (esp. if we still send a CSS bundle to the client lazily).
2. Inline global CSS on the page (i.e. exclude from bundling). This seems like the safest option: detect unscoped CSS on each page and prevent it from making it into the bundle. This is probably the safe/quick solution.

**Comment by drwpow** [comment]
We’ll be taking a look at CSS bundling in `0.21` next, as part of build improvements and fixes. Added this to the list of things to check!

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
