### ISSUE TITLE
💡 RFC: Builtin Icon Support

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#1374]
## Background & Motivation

- Icons and images are the two asset types that we've talked about having built-in support for in Astro.
- We would like to deliver on a couple of key features:
    - Make it easy to use external iconsets (`npm install [SOME-ICON-FONT-PACKAGE]` packages are notoriously heavy, bloated, and poor user experience).
    - Make it easy to use your own custom icons
    - Make it easy to combine multiple icons into a single "SVG spritesheet".
- @antfu has been exploring some really cool work to reference icons using iconify and then have Vite return the SVG in [this plugin](https://github.com/antfu/unplugin-icons), which was inspiration for me to pick this back up in Astro.

## Proposed Solution

- Add a new `Icon` component to Astro.
- **Proof of concept:** https://github.com/snowpackjs/astro/commit/b9af3dd21b6103e5486a1f982b299ed51d51bebf

```astro
---
import {Icon} from 'astro/components';
---
<div>
  <Icon collection="fa-solid" icon="rocket" />
  <Icon collection="fa-solid" icon="rocket" scale={4} color={'red'} />
</div>
```

## Detailed Design

The `Icon` component works by fetching the SVG data via iconify (internally, this just gets the SVG data from a big internal JSON object). SVG is returned as the component body.

## Limitations

- TODO in WIP: Currently there's no caching, but we can save a few ms per Icon render by caching the collection that gets loaded for future runs.
- TODO in the future: Currently there's no way to set a default collection, but this feels very similar to that same ask to set a default `<Code>` theme across your site.
- TODO in the future: How can this work with your own local icons, stored in `src/icons`? 

## Tradeoffs

Two important tradeoff callouts:

### 1. Using an `<Icon>` component vs. ESM imports

One nice thing about https://github.com/antfu/unplugin-icons is that every icon gets imported via ESM import, so that it's really clear to both users and tooling which icons are used. For example, when you use ESM imports you could scan your entire project ahead-of-time to find out which icons were used (more on why this matters in the next section).

We could ditch the `<Icon>` idea and just add something like `unplugin-icons` directly to our build pipeline, so that you'd do this instead:

```diff
- import {Icon} from 'astro/components';
+ import RocketIcon from 'icon:fa-solid/rocket';

- <Icon collection="fa-solid" icon="rocket" /> 
+ <RocketIcon /> 
```

Another perk of this system is that this would give us a natural hook to serve local SVGs with a similar API support. The current proposal is an API for popular remote iconsets only.

```
import RocketIcon from 'icon:local/rocket.svg';
// or
import RocketIcon from '../icons/rocket.svg';
```

### 2. No SVG spritesheet support

This approach intentionally doesn't implement the idea of SVG spritesheets. When you use any `<Icon>` component, you don't know which icons your project is using until after the build has completed and the Icons have been rendered inline. 

You could maybe do something clever, but this coincides with my own recent skepticism of the SVG spritesheet idea. Some quick reasons why I've cooled on this in favor of inline SVGs:
- It would be difficult to implement in development, given that Astro is unbundled and a spritesheet is a bundled concept.
- We would be responsible to implement most of this on our own, since no build tools (Snowpack, Vite, etc) support this SVG story afaik. Think SVG combining, fingerprinting, etc. Meanwhile, inline SVGs "just work".
- SVG spritesheets are more limited from inline SVGs, in a way that would break some iconsets (especially any duotone icons)
- Given the differences and how much more popular inline SVGs are than spritesheets, we increase our learning curve for the users who run into SVG issues.
- GZIP really reduces (removes completely?) the perf cost of repeated inline SVGs.

Inline SVGs are just so much more easy, lightweight, and less risky to get us stuck. I don't believe that this stops us from implementing a cool SVG spritesheet solution or [something else](https://css-tricks.com/svg-use-with-external-reference-take-2/#weird-future-stuff) in the future).

## Open Questions

- What about using icons with frameworks? Is this a reason to kick off a design around `import {Icon} from 'astro/react';`, `import {Icon} from 'astro/svelte';`, etc? 

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
I'd really love feedback on the Tradeoffs section, specifically comparing this proposal to an alternative design that leverages ESM imports instead of a dedicated Icon component.

**Comment by eyelidlessness** [comment]
(This isn't commentary on the proposal itself, but more generally about Astro's scope and priorities. But I think it's worth discussing in this context, and hopefully more broadly as well.)

I mean this in the most constructive way possible: I'm unclear on what Astro's scope is intended to be at this point. When it was first introduced, my impression was the scope is: component oriented framework-agnostic SSG[/SSR eventually] with partial hydration, with some special treats not typically available in those frameworks (eg `Markdown` component). Since then it's grown proposed to include quite a lot more than that.

Like, batteries included is/can be cool to a degree, it can help with many common use cases. This feels well beyond that to me?

One of the biggest challenges in the web space is mixing tooling to satisfy complex or specialized needs and use cases. The more opinionated and the larger the scope of any given piece of tooling, the less generally able it is to help mitigate that challenge. (Side note: this is a big part of why esbuild is doing so well in the bundler space, despite being feature-minimal and despite its lack of AST facilities being a deoptimization.)

I, personally, would rather see Astro focus on building helpful interfaces versus helpful features (apart from its core value proposition). By all means develop an icon solution if there's demand for it. But I'd rather see it as a more general plugin/build pipeline library than part of Astro main.

And... this is asking a lot from the community but I think there's precedent (renderer plugins, which I'm exceedingly proud to have helped influence) for defining that interface as a priority rather than defining the implementation or use case itself. If there's openness to this as a consideration as a stand-in for this RFC, I'd love to spend more of my brainpower on it even just to see things go in a more general and composable/interoperable direction.

**Comment by FredKSchott** [comment]
Well said, the idea of adding this as an external package and not built-in is noted. There’s actually nothing stopping this from being an external package today, so maybe we start there and then see how people like it.

I don’t think this is slippery slope situation.  There are only a few situations that we’ve considered handling in core like this: images, icons, and fonts.

**Comment by FredKSchott** [comment]
I'm now +1 on starting this as an external package for now, and then revisiting as we prepare for v1.0. As the RFC shows, there's too many different ways to do Icons and we really haven't explored any of them yet in Astro. I'd rather leave exploration to user land before we consider what core support looks like.

Note that Image and Font support will almost certainly still be built into Astro core. Unlike Icons, these use-cases are much more straightforward, and too important to leave to some external package.

**Comment by eyelidlessness** [comment]
> these use-cases are much more straightforward

They’re really very much not :(

> and too important to leave to some external package

Even your apparent competitor in this space (Vercel/Next) is very minimal in their ambitions but more importantly very permissive about external packages.

**Comment by jasikpark** [comment]
> I'm now +1 on starting this as an external package for now, and then revisiting as we prepare for v1.0. As the RFC shows, there's too many different ways to do Icons and we really haven't explored any of them yet in Astro. I'd rather leave exploration to user land before we consider what core support looks like.
> 
> Note that Image and Font support will almost certainly still be built into Astro core. Unlike Icons, these use-cases are much more straightforward, and too important to leave to some external package.

I'm definitely in favor of developing this as an external package.. I think there are at least a couple of features that would benefit the best from being fully sorted out in userspace as external packages unless it's truly necessary to be built by Astro.. then once there's a beloved leader package, it could be rolled into the Astro project if wanted.
