### ISSUE TITLE
🐛 BUG: interpolated expression inside HTML in <Markdown> component silently ignored

### ISSUE THREAD

**Issue by amagee** [snowpackjs/astro#1540]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

If I try to interpolate a Javascript expression inside HTML inside a `<Markdown>` element, I get no output at all.

### Steps to Reproduce

1. `npm init astro` using any template.

2. Create the following `.astro` file:

```
---
import { Markdown } from 'astro/components';
---
<html>
  <body>
    <div>
      <Markdown>
        <div>
          {"some text"}
        </div>
      </Markdown>
    </div>
  </body>
</html>
```

Output: none

Expected output: `some text`

**Comment by natemoo-re** [comment]
Following up on my previous comment, the team has decided to close out issues that have been confirmed as fixed by [astro@0.21.0-next.0](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.0), [astro@0.21.0-next.1](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.1), or [astro@0.21.0-next.2](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.2). Our hope is that this will help the [v0.21 milestone](https://github.com/snowpackjs/astro/milestone/1) remain as actionable as possible.

To verify that this issue has been fixed, you may
- Open a new [`astro@next` project on StackBlitz](https://astro.new/minimal@next)
- Locally upgrade to the `astro@next` preview
    ```shell
    npm i astro@next
    # If using Framework renderers...
    npm i @astrojs/renderer-name@next
    ```

If you think we made a mistake, **please reopen this issue**!

If you run into any other problems with `astro@next`, please [open a new issue](https://github.com/snowpackjs/astro/issues/new?assignees=&labels=0.21&template=---01-bug-report.yml&title=%F0%9F%90%9B+BUG%3Aastro@next).
