### ISSUE TITLE
🐛 BUG: syntax error on next sibling of <Markdown> element if the Markdown body ends with HTML

### ISSUE THREAD

**Issue by amagee** [snowpackjs/astro#1541]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

If:

1. I have a `<Markdown>` element in my page, and
2. The content of the `<Markdown>` element is either empty or ends with HTML, and
3. There is content after the end of the `<Markdown>` element,

then I get a syntax error that looks like `SyntaxError: [76:7]: Unexpected token: ','`.

### Steps to Reproduce

1. `npm init astro` using any template

2. Create the following `.astro` file:

```
---
import { Markdown } from 'astro/components';
---
<html>
  <body>
    <div>
      <Markdown>
        <div />
      </Markdown>
      oops
    </div>
  </body>
</html>
```

3. Output: `SyntaxError: [76:7]: Unexpected token: ','`

Expected: `oops`

Notes:

* Putting some text after the `<div />` inside the `<Markdown>` makes the problem go away
* Removing the `oops` makes the problem go away

**Comment by natemoo-re** [comment]
Following up on my previous comment, the team has decided to close out issues that have been confirmed as fixed by [astro@0.21.0-next.0](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.0), [astro@0.21.0-next.1](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.1), or [astro@0.21.0-next.2](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.2). Our hope is that this will help the [v0.21 milestone](https://github.com/snowpackjs/astro/milestone/1) remain as actionable as possible.

To verify that this issue has been fixed, you may
- Open a new [`astro@next` project on StackBlitz](https://astro.new/minimal@next)
- Locally upgrade to the `astro@next` preview
    ```shell
    npm i astro@next
    # If using Framework renderers...
    npm i @astrojs/renderer-name@next
    ```

If you think we made a mistake, **please reopen this issue**!

If you run into any other problems with `astro@next`, please [open a new issue](https://github.com/snowpackjs/astro/issues/new?assignees=&labels=0.21&template=---01-bug-report.yml&title=%F0%9F%90%9B+BUG%3Aastro@next).
