### ISSUE TITLE
🐛 BUG: <Markdown> -> HTML -> <Markdown> prematurely closes containing tag

### ISSUE THREAD

**Issue by amagee** [snowpackjs/astro#1542]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

If I have a `<Markdown>` element that contains HTML, which in turn contains another `<Markdown>`, then this causes the container of the outer `<Markdown>` element to be closed prematurely - that is, content that should be inside that container comes out outside of it.

### Steps to Reproduce

1. `npm init astro` with any template

Create the following `.astro` file:

```
---
import { Markdown } from 'astro/components';
---
<html>
  <body>
    <section style="background-color: red;">
      <Markdown>
        <div>
          <Markdown>
            red
          </Markdown>
        </div>
        padding
      </Markdown>
      should be red
    </section>
  </body>
</html>
```

Output:

```
red
padding
should be red
```

however "padding" and "should be red" are not on a red background because they have been moved out of their containing `<section>`.

Expected: same, but all the text should be on a red background.

Notes:

* `padding` is only necessary to work around https://github.com/snowpackjs/astro/issues/1541
* Removing the inner `<Markdown>` element fixes the issue
* The issue exists in the generated HTML; it's not just the browser deciding it doesn't like the nesting and messing with it as it would if you did something like putting a `<div>` inside a `<p>`. The generated HTML is

```
<!DOCTYPE html><html><head></head><body><section style="background-color: red;"><div><p class="astro-ldKR6c5M">red</p></div></section><p>padding</p>
      should be red
    </body></html>
```

**Comment by natemoo-re** [comment]
Following up on my previous comment, the team has decided to close out issues that have been confirmed as fixed by [astro@0.21.0-next.0](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.0), [astro@0.21.0-next.1](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.1), or [astro@0.21.0-next.2](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.2). Our hope is that this will help the [v0.21 milestone](https://github.com/snowpackjs/astro/milestone/1) remain as actionable as possible.

To verify that this issue has been fixed, you may
- Open a new [`astro@next` project on StackBlitz](https://astro.new/minimal@next)
- Locally upgrade to the `astro@next` preview
    ```shell
    npm i astro@next
    # If using Framework renderers...
    npm i @astrojs/renderer-name@next
    ```

If you think we made a mistake, **please reopen this issue**!

If you run into any other problems with `astro@next`, please [open a new issue](https://github.com/snowpackjs/astro/issues/new?assignees=&labels=0.21&template=---01-bug-report.yml&title=%F0%9F%90%9B+BUG%3Aastro@next).
