### ISSUE TITLE
🐛 BUG: Stray comma rendered when slot fallback includes component followed by HTML content

### ISSUE THREAD

**Issue by innermatrix** [snowpackjs/astro#1605]
### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Rendering a component like

```
<html>
  <body>
    <slot>
      <BodyComponent />
      <div>two</div>
    </slot>
  </body>
</html>
```

ends up with a `,` between the content of `BodyComponent` and the `div` that follows it

### Steps to Reproduce

Look at the rendering of `index.astro` in supplied MWE. The component causing the problem is `MainComponent.astro`

### Link to Minimal Reproducible Example (Optional)

https://stackblitz.com/edit/astro-dj3jh6

**Comment by natemoo-re** [comment]
Following up on my previous comment, the team has decided to close out issues that have been confirmed as fixed by [astro@0.21.0-next.0](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.0), [astro@0.21.0-next.1](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.1), or [astro@0.21.0-next.2](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.2). Our hope is that this will help the [v0.21 milestone](https://github.com/snowpackjs/astro/milestone/1) remain as actionable as possible.

To verify that this issue has been fixed, you may
- Open a new [`astro@next` project on StackBlitz](https://astro.new/minimal@next)
- Locally upgrade to the `astro@next` preview
    ```shell
    npm i astro@next
    # If using Framework renderers...
    npm i @astrojs/renderer-name@next
    ```

If you think we made a mistake, **please re-open this issue**!

If you run into any other problems with `astro@next`, please [open a new issue](https://github.com/snowpackjs/astro/issues/new?assignees=&labels=0.21&template=---01-bug-report.yml&title=%F0%9F%90%9B+BUG%3Aastro@next).
