### ISSUE TITLE
💡 RFC: [Next] Create preprocessing infrastructure like svelte-preprocess

### ISSUE THREAD

**Issue by AsyncBanana** [snowpackjs/astro#1694]
### Background & Motivation

Currently, Astro has limited support for customizing preprocessing in Astro components. Astro supports Sass, Typescript, and style scoping built-in, but there is not much beyond that. It would be better to create a modularized preprocessing setup to support a wider variety of template languages like Pug, compile to JavaScript languages like Coffeescript, and CSS supersets like Stylus or Less. A good example of a tool that does this is [Svelte Preprocess](https://github.com/sveltejs/svelte-preprocess) for Svelte components.

### Possible solutions

A tool that allows people to create plugins that preprocess Astro component files, so you could pass a plugin list in the Astro config and use different preprocessors through the `lang` attribute of tags, like [Svelte Preprocess](https://github.com/sveltejs/svelte-preprocess). Additionally, it would be optimal if official plugins were made for the most popular tools, like renderers in Astro currently. It would also be helpful if some official plugins were added by default to make it easy, but that would make it less minimal by default, which could be considered a negative.

### Alternatives considered

Vite plugins might work, although I do not understand Vite's custom component handling well enough yet to know whether that would actually work.

### Risks, downsides, and/or tradeoffs

The main downside would be the development time taken to make this, which hopefully would not be too much.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by AsyncBanana** [comment]
> I think allowing preprocessing of everything is an interesting idea! One thing that comes to mind though is that we need for the template section to still have all of the directives and the component tags before Astro processes them. With something like Pug would that be possible?

@matthewp It should be, as there are projects that have used Pug to compile to JSX successfully.

**Comment by matthewp** [comment]
- Styles should be allowed in 0.21 via adding Vite plugins.
- Markdown does something similar, could that idea be explored?
- TypeScript is already supported.
  - Supporting other languages probably could not happen due to need to scan frontmatter for imports/exports.
- Preprocessing the template is probably not doable pre-1.0.
- Language tools / vscode would be challenging.

**Comment by matthewp** [comment]
Hey @AsyncBanana 👋, we talked about this on the RFC call and the consensus was that it felt too early to proceed with adding preprocessing infrastructure into Astro at this time. I added notes from the call above.

We did however feel that there might be opportunities to give *more specific* (rather than general) hooks when there are specific use-cases. For example, allowing TypeScript inside of a `<script>` tag is something we *might* be able to provide.

If you are interested in this approach and have such use-cases, please create another RFC about that. Thanks for submitting, this was a fun one to discuss!

**Comment by AsyncBanana** [comment]
Ok, thanks for discussing it!
Even if the extent of the preprocessing was the ability to use plugins to process `<script>` and `<style>` tags in Astro component files, that would still be very helpful.
