### ISSUE TITLE
💡 RFC: Commit to static URL attribute value handling

### ISSUE THREAD

**Issue by jonathantneal** [snowpackjs/astro#1785]
### Background & Motivation

I would not like Astro to modify relative static URLs used as attribute values. Such attributes include but are not limited to `src`, `href`, and `srcset`.

From the [current documentation](https://docs.astro.build/reference/api-reference/#astroresolve):

> Astro _does not_ resolve relative links within HTML, such as images:
>
> ```html
> <img src="../images/penguin.png" />
> ```
>
> The above will be sent to the browser as-is.

That’s it. Forward these values as static content, as-is. Allow the client to handle these values, whether by resolving URLs relative to the current page URL or relative to the current [base URL](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element), or by handling URLs [some other way](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html).

A relative URL would be defined by the following criteria:
- URLs beginning with any protocol using an [official IANA-registered scheme](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml); or,
- URLs beginning with any path root (`/`); or,
- URLs beginning with any path dot (`.`, or an ASCII case-insensitive match for [`%2e`](https://url.spec.whatwg.org/#single-dot-path-segment)).

### Proposed Solution

Follow the proposed behavior, which is also the documented behavior.

### Alternatives considered

An alternative would be to interpret relative URLs differently than other URLs (or any other static content). This would introduce many questions and would require many assumptions as to the 'base' URL that the relative URL is _relating_.

- Would a relative URL be relative to the current source file?
  - If so, would a relative URL match a path relative to the source (e.g. `./_assets/image.avif`) or to the compiled result (e.g. `./assets/image.avif`)?
- Would a URL like `assets/image.avif` need to be considered a relative URL?
  - If so, would [aliasing](https://github.com/snowpackjs/astro/pull/1747) be applied?
- Would a relative URL need to consider whether a base URL was defined?

With every decision, expectations of static relative URLs would verge further and further from HTML itself.

### Risks, downsides, and/or tradeoffs

Resolving URLs relative to the source file need to be handled some other way. Currently, this is handled with `Astro.resolve`.

From the [current documentation](https://docs.astro.build/reference/api-reference/#astroresolve):

> If you want it to be resolved relative to the `.astro` file you are working in, use `Astro.resolve`:
>
> ```html
> <img src={Astro.resolve('../images/penguin.png')} />
> ```

<br />

This proposal does not prohibit a future proposal that could transform non-IANA-registered schemes.

```html
<img src="rel:../images/penguin.png" />
```

Depending on the proposal, it may need to address the questions from the '**Alternatives considered**' section.

### Detailed Design

Follow the proposed behavior.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
I know that there is interest in a more helpful syntax to make relative URLs for things like `<img src>` and `<link href>` easier to use. This has been a point of trickiness in the past.

Instead of proposing the negative ("do nothing") can we propose a solution that solves for this user need AND helps finalize our default `src` and `href` handling? For example, one of the main ideas that's been proposed has been something like `src:relative`. I don't see this mentioned here at all.

Totally okay to chat with contributors/Discord before creating the RFC if you're still trying to understand the problem & user needs!

**Comment by matthewp** [comment]
When we did Astro.resolve there was discussion of a shorthand syntax, something like `<img relative:src="./images/penguin.png" />`.

I think this is going to be important for SSR, because we need to build able to build out `src/` assets at build time without rendering the HTML. If we could enforce that the usage of `relative:` (or some other prefix) as being static-strings-only, that would cover our needs for SSR.

**Comment by jonathantneal** [comment]
This RFC is superseded by https://github.com/snowpackjs/astro/issues/1842
