### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#365]
We've had issues in the past where some bugs (especially those related to module resolution) are not caught by integration tests due to have we have the monorepo set up and the use of snowpack's `workspaceRoot`.

We would like to have some integration tests that run to smoke test released versions. They might do:

1. Run `npm init astro` and step through the questions.
2. Start up `astro dev` and make sure it doesn't crash. Fetch the HTML from a few routes and verify its content.
3. Run the build `astro build` and make sure it doesn't crash. Check that the correct output was created.

**Comment by drwpow** [comment]
So in order to use the local versions of the templates, I think we need git tags. I believe changesets has built-in support for git tags, but only if you use `changeset release` (which makes sense, because you want the git tag to match the npm tag, which means it should happen at that step and not necessarily coinciding with a `package.json` bump).

I think using changesets to release to npm should either be part of this ticket, or blocking it.

**Comment by FredKSchott** [comment]
Done by @drwpow
