### ISSUE TITLE
🐛 `throw Error()` is not working.

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#526]
![image](https://user-images.githubusercontent.com/10626596/123183644-914e4080-d457-11eb-9ffd-884013812735.png)

### Bug Report: Quick Checklist

- [ ] I am on the latest version of Astro & all plugins. 13.0.6 in the astro-docs repo.
- [x] I am on an ESM Node.js version (`v12.20.0+, v14.13.1+, or v16.0.0+`)
- [x] I use package manager: (Fill in: npm, yarn, pnpm, etc).
- [x] I run Astro on OS: (Fill in: Windows, Mac, Linux, etc). macOS 11

### Describe the bug

An astro file with `throw Error('help')` will not build.

### Steps to reproduce

1. clone https://github.com/jasikpark/astro-docs/commit/3360151d050793eba23806d2cc55c8ab3f8a3309
2. `yarn`
3. `yarn build`

### Expected behavior

A site that hopefully builds or produces a different error than below:

```
[20:03:01] [snowpack]   └── is-plain-obj@3.0.0 (dedupe)
[20:03:01] [snowpack] └── astring@1.7.5 (dedupe)
[20:03:03] [snowpack] Build Result Error: There was a problem with a file build result.
[build] Error: SyntaxError: This experimental syntax requires enabling the parser plugin: 'throwExpressions' (9:4)
    at buildStaticPage (file:///Users/calebjasik/Github/astro-docs/node_modules/astro/src/build/page.ts:95:40)
    at file:///Users/calebjasik/Github/astro-docs/node_modules/astro/src/build.ts:78:9
    at async Promise.all (index 0)
    at build (file:///Users/calebjasik/Github/astro-docs/node_modules/astro/src/build.ts:75:5)
    at buildAndExit (file:///Users/calebjasik/Github/astro-docs/node_modules/astro/src/cli.ts:16:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Anything else?

Add any other info about the problem here, if useful. Delete this section if not used.

**Comment by rbrishabh** [comment]
Hey! I can help with this!
Can you help me with where to start?

**Comment by matthewp** [comment]
I don't think this *should* build, because it could mean deploying an incorrect version of your site. But we should surface the underlying error.

@rbrishabh I'd start by creating a test. You can find some build related tests in the packages/astro/test directory. Here's 1: https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/test/astro-sitemap.test.js

You'll want to create a new test file and a fixture (in packages/astro/test/fixtures) that throws in the frontmatter.

As far as the bug, I suspect that perhaps we're not surfacing this error because of the way that we build pages in parallel. Making adding a `.catch` on this problem will be a start? https://github.com/snowpackjs/astro/blob/91e11aee2a57b6613fc824168950d7e3c7b0e144/packages/astro/src/build.ts#L74
