### ISSUE TITLE
🐛 BUG: Falsy conditional expression renders "false"

### ISSUE THREAD

**Issue by mihkeleidast** [snowpackjs/astro#679]
### What package manager are you using?

npm

### What operating system are you using?

WSL/Ubuntu

### Describe the Bug

When using conditional expressions in Astro components, it renders "false" as the result when the condition does not match.

For example:
```
{!!notes && (
  <Markdown content={notes} />
)}
```
outputs "false". React/Preact do not render falsy values at all, so this is a bit unexpected.

### Steps to Reproduce

1. Add the example above to a component and observe what is rendered when `notes` is truthy or falsy.

**Comment by matthewp** [comment]
Note that React/Preact do render at least some falsy values, `0` gets rendered for example.

**Comment by matthewp** [comment]
We actually have this implemented and tested here: https://github.com/snowpackjs/astro/blob/main/packages/astro/test/astro-expr.test.js#L78-L82

Can you provide more context, like a full .astro file that shows this doesn't work for you?

**Comment by mihkeleidast** [comment]
I can provide a better example tomorrow, but as far as I can understand from the test, it only checks if the element is (not) rendered., not what the actual output is. For example, [this](https://github.com/snowpackjs/astro/blob/main/packages/astro/test/fixtures/astro-expr/src/pages/falsy.astro#L6) renders "false" as a string, but it shouldn't.

**Comment by mihkeleidast** [comment]
I could swear that the example in the original post rendered "false" yesterday, but can't reproduce it anymore. Sorry for the trouble, and I'll take screenshots next time :)

**Comment by tony-sull** [comment]
Ran into this one as well, turns out it only hits if the falsy check is in a child component...?  [Here's a repro](https://github.com/tony-sull/repro-astro-renders-false) based on the barebones starter app

The homepage component works correctly - when directly checking for an array's length it only renders to the DOM if `length > 0`

In `Child.astro`, it tries 3 different arrays.  Two are the same arrays from the main homepage component, passed in as props.  The third is an internal array I added to see if it's specific to Astro.props or any flasy check in the child.

- The child component renders the first array with 3 items, then `false` for each of the empty arrays

**Comment by tony-sull** [comment]
I've got a hunch it's a serialization issue

I could see this happening if Astro passes through the child component once and gets a boolean, then throwing out all content after the `&&`.  If that boolean gets serialized to a string, Astro may be finding that "false" string later (with no content after it since that was already pruned), but the "false" string is valid so it's getting thrown into the DOM

**Comment by matthewp** [comment]
So the issue is that fragments don't handle falsey values. Our logic for elements and fragments is slightly different here. Good  news because this should be easy to write a test for and fix.
