### ISSUE TITLE
📘 DOC: Rework `theme.css` to use HSLA composition for easier color definition

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#755]
I want to make defining extra colors in the theme easier, as @FredKSchott has run into, by rewriting the theme w/ HSLA composition as explained in [The Power of Composition with CSS Variables](https://blog.maximeheckel.com/posts/the-power-of-composition-with-css-variables/).

We might also add comments explaining how the composition all works...

## Excerpt from [The Power of Composition with CSS Variables](https://blog.maximeheckel.com/posts/the-power-of-composition-with-css-variables/):
```css
--base-blue: 222, 89%; /* All my colors here share the same hue and saturation */
/*
  Here I declared my color palette.
  Each color is a partial value
*/
--palette-blue-10: var(--base-blue), 10%;
--palette-blue-20: var(--base-blue), 20%;
--palette-blue-30: var(--base-blue), 30%;
--palette-blue-40: var(--base-blue), 40%;
--palette-blue-50: var(--base-blue), 50%;
--palette-blue-60: var(--base-blue), 60%;
--palette-blue-70: var(--base-blue), 70%;
--palette-blue-80: var(--base-blue), 80%;
--palette-blue-90: var(--base-blue), 90%;
--palette-blue-100: var(--base-blue), 100%;
/*
  Here I compose a color based on its meaning:
  - primary and emphasis are composed by using --palette-blue-50
  - they use a different opacity level thus they have different meaning:
    - primary is a bold color used for buttons and primary CTA
    - emphasis is used to highlight content or for the background of my callout cards
*/
--primary: hsla(var(--palette-blue-50), 100%);
--emphasis: hsla(var(--palette-blue-50), 8%);
```

cc: @jgil-r

**Comment by jgil-r** [comment]
@natemoo-re Do you have any thoughts on transitioning colors to hsla? A lot of this is based off of the article @jasikpark shared above. I was thinking we have a base color for all 9 colors, using just the hue and saturation value.
ex: 
```css
--color-base-white: 0, 0%;
--color-base-gray: 215, 14%;
```

It looks like `gray` is the only color where we can set up a full palette. For black, white, blue, green, orange, purple, red, and yellow we can just hard code the lightness and opacity values as needed since it doesn't look like we need many variations of those. So, we would be able to get rid of colors like `--color-blue-rgb`.

**Comment by natemoo-re** [comment]
I'm fine with switching to `hsla` for all the colors! I do think having preset saturation and lightness values is a good idea from the design side of things. Otherwise you can easily find yourself in a situation where colors get out of sync.

**Comment by jgil-r** [comment]
#790 closes this one
