### ISSUE TITLE
📘 DOC: about link redirecting to 404

### ISSUE THREAD

**Issue by eddieduro** [snowpackjs/astro#771]
This link is pointed to https://astro.build/getting-started which is throwing a 404

_This about section_
![image](https://user-images.githubusercontent.com/7972722/126265505-644fd6a5-9721-4cfb-97ea-87e77e8500b1.png)

404 error:
![image](https://user-images.githubusercontent.com/7972722/126265550-6b4cf871-2b21-438e-967b-4a07fcba849d.png)

**Comment by jasikpark** [comment]
I believe this needs to be fixed by changing https://github.com/snowpackjs/astro/blob/main/vercel.json a bit :0

Currently I think both `https://astro.build/` and `https://docs.astro.build` redirect to `/getting-started` and `/chat` on both domains redirects to the discord link.

I think keeping both redirecting to the discord link is perfectly fine, but the other redirect is not the best.

**Comment by jasikpark** [comment]
Closed by #776
