### ISSUE TITLE
📘 DOC: E-commerce sites with large catalogs

### ISSUE THREAD

**Issue by joostmeijles** [snowpackjs/astro#811]
I don't full understand the vs. NextJS comparison (https://docs.astro.build/comparing-astro-vs-other-tools#nextjs-vs-astro).
It states "Astro ... best with highly static websites (like content and eCommerce websites)...", but I believe static site generation for an e-commerce website with a large catalog is not possible using pure SSG as build times will be too long.

What is the performance of Astro SSG builds?
Does Astro provide incremental-static-re-generation to allow scaling for large catalogs?

**Comment by FredKSchott** [comment]
eCommerce was added as an example of a mostly-static site, which Astro is (generally speaking) better at because it can greatly reduce the JS payload of static content on the page. You're right that SSG breaks down at large size projects, but this comparison is meant as a focus on the user experience and not the dev experience.

If you have suggestions for how to improve these docs, I'm all ears! This page is fairly new and I'm sure there are ways that we could clarify. Maybe add a note on project size to the "Astro is still in beta" warning in the first section?
