### ISSUE TITLE
💡 RFC: Finalize Project Folder Structure

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#901]
## Background & Motivation

- We've received some feedback that our project layout is confusing to users. 
- Some problems can be solved with smaller features, but I wanted to take this as a chance to explore other folder structures before committing to our current one. If a better design solves a problem, it's worth considering before we reach v1.0.

### Issues related to structure that users have reported as confusing: 
- Referencing assets for the frontend. 
- Colocating components with the pages that they are used on.
- confusion over why some special dirs are top-level (`public/`) and others are nested within the src directory (`src/pages`).
- confusion over why some some directories within the src directory (`src/pages`) are special, and others aren't.
- others?

### Today's Project Structure

```
├── src/
│   ├── components/
│   ├── layouts/
│   └── pages/
│       └── index.astro
├── public/
└── package.json
```

## Proposed Solution

_In all design proposals: `public/` has been renamed to `static/` & `pages/` has been renamed to `routes/`. This isn't super important for the purpose of comparing overall designs, can be debated separately from the designs themselves._ 

## Design A

- Slight variation on what we have today, where everything moves out of the `src/` directory and into the top-level. Alt. variation: `static/` moved into `src/`.

```bash
- components/
- themes/
- static/
- layouts/
- routes/  # Every file inside of pages corresponds to a page/route
- package.json
```

#### Alt. Variation

```bash
src/
  - components/
  - themes/
  - static/
  - layouts/
  - routes/  # Every file inside of pages corresponds to a page/route
- package.json
```

#### Alt. Variation

```bash
- routes/  # Every file inside of pages corresponds to a page/route
- static/
- src/
  - components/
  - themes/
  - layouts/
- package.json
```

#### PROS (compared with other proposals): 
- "clean" folder organization
- Seems to be working well for next.js
- not too different from what we have today.

#### CONS (compared with other proposals): 
- no colocation, things live far away from their route.

## Design B

- A variation incorporating changes from https://gist.github.com/rauschma/91b04ca958f3461106b2851dcaa270e7
- Assets (mainly, images) can now be colocated with their page.
- components should still live in `components/`, since they would need to be bundled in the final build and doing so in the `routes` directory would break the "file tree = URL structure" promise.

```
- components/
- themes/
- layouts/
- routes/
  - favicon.ico
  - index.astro
  - core-concepts/
    - page1.md
    - page2.md
    - some-image.png
- router.js  # defines your routes and pages inside of `routes/`
- package.json
```

#### PROS: 
- `static` and `routes` combined into one concept
- file tree = URL structure
- Seems to be working well for @rauschma

#### CONS:
- need some form of config to know what is a page (router.js, in the example below)
- unclear/hidden difference between a JS file in `routes/` (shipped to browser, untouched) or one in components (compiled, bundled, etc).

## Design C

- Like today's design, but adds support for non-page components inside the `routes/` directory.
- Anything inside of `routes/` that starts with a `$` becomes a public facing page.
- Anything else inside of `routes/` is private, not a page.

```
- components/
- themes/
- static/
- layouts/
- routes/
  - about/
    - $index.md  # a page
    - SomeComponent.astro  # private component
    - SomeComponent.jsx
  - $index.astro
  - $rss.js
  - [tag]/
    - $index.astro
```

#### PROS: 
- you can nest components and layouts inside of routes
- supports other types of pages, like JS files generating RSS feeds, and API routes.

#### CONS:
- the $ needed by all routes is a bit noisy, esp. for markdown.
- may feel most "unfamiliar" of all the proposals

## Design D

- Like the previous design, but public page are now opt-out instead of opt-in.
- Anything that starts with a `_` is private, and won't become a route.
- Anything else becomes a public page.

```
- components/
- themes/
- static/
- layouts/
- routes/
  - about/
    - index.md  # a page
    - _components/
      - SomeComponent.astro  # private component
      - SomeComponent.jsx
  - index.astro
  - rss.js
  - [tag]/
    - index.astro
```

#### PROS: 
- no need for a special $ symbol, underscore = private is a bit more familiar

#### CONS:
- more boilerplate than the previous design 
- opt-out pages means "I accidentally made that file into a public page" is more likely 

## Next Steos

- Discuss these designs
- Are there other ideas not listed here? Add them via comment!
- commit to a v1.0 layout, and break any follow-up action items into separate issues

**Comment by jasikpark** [comment]
I am in favor of keeping the current file structure, but enforcing some of the bits that aren't today, like the idea that `public/` is a folder that gets copied without processing - that's what the docs claim, but css will get chunked even though it's in public and typescript will get compiled to javascript..

`static/` might be clearer at the start to some people, but `public/` honestly works just as well imo. 

I'm glad to see this RFC though!

**Comment by kosich** [comment]
Currently `layout` and `components` folders seem like they have some special meaning in Astro. I tend to organise my projects Feature/Page-wise, not type-wise. So my current Astro project looks something like this:

```
- src
  - Events
    - EventPage.astro
  - Home
    - HomePage.astro
    - EventCard.astro
  - shared
    - Layout.astro
    - Header.astro
    - ...
  - pages
    - index.astro
    - events
      - index.astro
      - a.md
      - b.md
      - ...
```

_I use a similar approach in a nextjs project_

Files in the `src/pages` just aggregate data and pass it to the `src/<Feature>/<Feature>Page` page. And `<Feature>Page` defines display logic and uses a layout it needs. Though I haven't yet used neither "collections" feature, nor RSS, so I might be missing something. _I also tried moving `pages` outside `src`, but got some issues with that, so had to revert._

It would make sense to me to keep some static files (like images) inside both `pages` (per event) and inside feature folders, like `src/Home`, for design related assets.

On **B**: feels a bit too complex for some cases. Could that be an opt-in (via a plugin?), where one can create a `route-config.js` file in, say, `pages/blog/posts` to customise the default behaviour?

On **C** & **D**: Imho, mixing "routes" with components might be confusing and restricting on bigger projects — I personally don't have a hands on experience with such approach, so I'm a bit wary.

P.S: thanks for the awesome project!

**Comment by devsmitra** [comment]
I like the current folder structure simple and easy to start with. but we can keep routes out of src, it's just one level of segregation between public and private files.

I use a similar approach in the Next.js project. 

```
src/  #Anything that is inside src is private, and won't become a route.
  - components/
  - themes/
  - layouts/
pages/  # Every file inside of pages corresponds to route
static/
package.json
```

**Comment by radiosilence** [comment]
@devsmitra pages are a form of source, mind. I don't really want to be having to include '../../src/components' inside a page.

**Comment by tony-sull** [comment]
Just my two cents, but I'm partial to having all source live under `/src` and **not** co-locating components and routes/pages.  My preferred folder structure (below, at the bottom) would look mostly like **Option A (alternate)**

### For `/src`,

I've seen a few benefits.  It can be a bit more clear if all source code for the build lives under that one `/src` directory.

More importantly for me, it frees up the root to hold other types of project-specific files you may want in source control.  Including a folder for design assets, documentation, and tests can all like next to the `/src` directory rather than being mixed in with `pages` or `components`.

### For **not** co-locating components

I've done this on a few projects and have seen it lead towards a tendancy to lose track of what components can (and should) be reused across the project.  Especially on a larger project with teams each owning different feature areas, they will almost certainly make their own components that really should be shared.

Though, I do tend to break out my `components` directory by feature area if I end up with enough components (see below)

## All that said

I'm a big fan of how configurable 11ty's project structure is.  You don't need to include a config file at all and it just works, but you can also override all of the default directory structure settings.  The caveat is that two 11ty projects can look drastically different and make onboarding a bit harder.  My usual setup will look similar to

```
src/
  - components/ 
    - common/
      - controls/ # Basic controls (button, checkbox, lists, etc)
      - forms/
      - nav/
    - auth/
    - settings/
  - themes/
  - static/ # or assets
  - layouts/
  - routes/  # Every file inside of pages corresponds to a page/route
- package.json
- ```

**Comment by FredKSchott** [comment]
This is fantastic feedback everyone, thank you for taking the time to respond! I'm glad to hear that colocating code with pages isn't the "must have" feature that I feared it might be. Also great to see some alternative layouts that give a "per-feature" organization to your `src/` directory, like in  @kosich's post.

Dynamic routing (when it lands) may also unlock some other options for colocating assets with their markdown. For example, you could have a single `[...blog].astro` file that handles the routing for all markdown posts. And then, your posts could live inside of some `src/posts/...` directory and could reference colocated images, etc.

```
src/
  posts/
    2021/
      my-first-post.md
      image1.png
      image2.png
  ...
  pages/
    blog/
      [...post].astro # handles the layout and routing for every blog post
```

**Comment by naiyerasif** [comment]
As far as I can see, Astro currently resolves routes through directory structure. But what if the routes are not dependent on the directory structure; what happens if they depend on custom generated slug (e.g., slugs generated by [slugify](https://github.com/sindresorhus/slugify)). This could be relevant when people migrate applications from other frameworks (like Gatsby). Keeping this in mind,

- Routing should be driven by convention but there should be some configuration to override it, so that people can maintain the URL immutability when they migrate from other frameworks
- I've seen instances where markdown files may not reside in `src` folder. The usecase is where content is managed independent of source code (e.g., content driven by services like [Forestry](https://forestry.io/)). Same goes for images as well. Providing a configuration-based approach should handle such cases effectively.

**Comment by jonathantneal** [comment]
I like what A, C, and D are doing, where most files are nearly identical to public, but where anything that starts with `$` could represent a dynamic route, and anything starting with `_` could represent a private resource.

**Comment by FredKSchott** [comment]
RFC Call: Committing to current overall project structure, but highlighted some smaller points for discussion before  v1.0 lands:

1. `static/` instead of `public/` ?
1. `src/routes/` instead of `src/pages/` ?
1. `pages/` instead of `src/pages/`? 
1. Config based routing?
1. The idea of non-page components/assets living next to a page? (colocation)
